apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  # parallelism: 2
  # completions: 10
  template:
    metadata:
      name: test-job
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo","hello k8s job"]
      restartPolicy: Never