apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
spec:
  serviceName: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80